# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_player_1', models.IntegerField(default=None, max_length=40)),
                ('id_player_2', models.IntegerField(default=None, max_length=40)),
                ('pending_request', models.BooleanField(default=False)),
                ('gesture_1', models.CharField(default=None, max_length=40)),
                ('gesture_2', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
